# Generated by Django 4.0.3 on 2022-04-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, verbose_name='ISBN number of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(max_length=20, verbose_name='Publication date of the book'),
        ),
    ]
